#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $DARK_REPO ==darkbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $DARK_REPO ==DARKBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $DARK_REPO =~ $regex ]]
    then
        if [[ $DARK_REPO_BRANCH ]]
        then
            echo "${DARK_REPO}/archive/${DARK_REPO_BRANCH}.zip"
        else
            echo "${DARK_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_starter () {
    local zippath
    zippath="mydarkbot.zip"
    echo "••• DOWNLOADING DARKBOT •••"
    wget -q $(_get_repolink) -O "$zippath"
   DARK_PATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    rm -rf "$zippath"
    sleep 5
    cd $HELL_PATH
    echo "••• STARTING DARKBOT •••"

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m darkbot
}

_starter
